name: "Build and Test Komiser PRs"
on: pull_request

jobs:
  build_test_dashboard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: "dashboard/package-lock.json"

      - run: npm ci
        working-directory: dashboard

      - run: npm run lint
        working-directory: dashboard

      - run: npm test
        working-directory: dashboard

      - run: npm run build
        working-directory: dashboard

  build_test_cli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          cache: true
          cache-dependency-path: go.sum
          go-version: 1.21

      # FIXME: https://github.com/golangci/golangci-lint-action/issues/677
      # - name: golangci-lint
      #   uses: golangci/golangci-lint-action@v3
      #   with:
      #     skip-pkg-cache: true

      - name: Install dependencies
        run: go mod download

      - name: Test
        run: make test

      - name: Build
        run: make build
