on:
  pull_request:
    types: [closed]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Comment on PR
        if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'hacktoberfest-accepted') }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.GH_ACTIONS }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            A heartfelt thank you, @${{ github.event.pull_request.user.login }}, for your enthusiastic involvement in Hacktoberfest! To express our gratitude, we've crafted a special virtual badge just for you. Don't hesitate to showcase it on your social media profiles and share the love by mentioning Komiser in your posts. Your contribution means the world to us!
            ![Image](/images/hacktoberfest-badge.svg)
