name: Lint
on: pull_request

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          cache-invalidation-interval: 15
          args: --timeout=10m
          version: v1.59
          skip-cache: true
